/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $: typeof import('jquery')['default']
  const Routes: typeof import('$app/utils/routes')
  const jQuery: typeof import('jquery')['default']
}
